### ISSUE TITLE
nature of index of the nodes in file-input in Maze class

### ISSUE THREAD

**Issue by MoeBensu** [tameraktasTU/AlgoDatSS19-Test#8]
Is it safe to assume that mazegrid() via file input is going graphs has always by 1-incremented nodes? 
upper left node is always 0 then 1 , 2 .. and so on. This is the case of the constructor Graph(int V), but not sure about Graph(In in).

The other part of the question is, the test of mazegrid with a string input shouldn't be dependent on the order of adjacent list of each node, right? cuz it is.

**Comment by flo-bit** [comment]
mazegrid() is supposed to create it's own grid so no file input necessary. For Graph(In in) just look at the method, looks pretty straightforward to me (but is not needed for the homework at all).

regarding the mazegrid() test, yeah that one (actually not _only_ that one ^^) was lazy coding on my behalf, order shouldn't matter but in the test it does. If anyone wants to fix that be my guest ;)
